// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"

	"github.com/go-pg/pg/v10"
	"github.com/go-pg/pg/v10/orm"
)

const condition = "?.? = ?"

// base filters
type applier func(query *orm.Query) (*orm.Query, error)

type search struct {
	appliers []applier
}

func (s *search) apply(query *orm.Query) {
	for _, applier := range s.appliers {
		query.Apply(applier)
	}
}

func (s *search) where(query *orm.Query, table, field string, value interface{}) {
	query.Where(condition, pg.Ident(table), pg.Ident(field), value)
}

func (s *search) WithApply(a applier) {
	if s.appliers == nil {
		s.appliers = []applier{}
	}
	s.appliers = append(s.appliers, a)
}

func (s *search) With(condition string, params ...interface{}) {
	s.WithApply(func(query *orm.Query) (*orm.Query, error) {
		return query.Where(condition, params...), nil
	})
}

// Searcher is interface for every generated filter
type Searcher interface {
	Apply(query *orm.Query) *orm.Query
	Q() applier

	With(condition string, params ...interface{})
	WithApply(a applier)
}

type UserSearch struct {
	search

	ID        *int64
	CreatedAt *time.Time
}

func (us *UserSearch) Apply(query *orm.Query) *orm.Query {
	if us == nil {
		return query
	}
	if us.ID != nil {
		us.where(query, Tables.User.Alias, Columns.User.ID, us.ID)
	}
	if us.CreatedAt != nil {
		us.where(query, Tables.User.Alias, Columns.User.CreatedAt, us.CreatedAt)
	}

	us.apply(query)

	return query
}

func (us *UserSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if us == nil {
			return query, nil
		}
		return us.Apply(query), nil
	}
}

type CommentSearch struct {
	search

	ID               *int64
	Content          *string
	LikesCnt         *int64
	UserID           *int64
	IsVisible        *bool
	CreatedAt        *time.Time
	InterviewID      *int64
	QuestionID       *int64
	TestAssignmentID *int64
	TaskID           *int64
	IDs              []int64
	ContentILike     *string
}

func (cs *CommentSearch) Apply(query *orm.Query) *orm.Query {
	if cs == nil {
		return query
	}
	if cs.ID != nil {
		cs.where(query, Tables.Comment.Alias, Columns.Comment.ID, cs.ID)
	}
	if cs.Content != nil {
		cs.where(query, Tables.Comment.Alias, Columns.Comment.Content, cs.Content)
	}
	if cs.LikesCnt != nil {
		cs.where(query, Tables.Comment.Alias, Columns.Comment.LikesCnt, cs.LikesCnt)
	}
	if cs.UserID != nil {
		cs.where(query, Tables.Comment.Alias, Columns.Comment.UserID, cs.UserID)
	}
	if cs.IsVisible != nil {
		cs.where(query, Tables.Comment.Alias, Columns.Comment.IsVisible, cs.IsVisible)
	}
	if cs.CreatedAt != nil {
		cs.where(query, Tables.Comment.Alias, Columns.Comment.CreatedAt, cs.CreatedAt)
	}
	if cs.InterviewID != nil {
		cs.where(query, Tables.Comment.Alias, Columns.Comment.InterviewID, cs.InterviewID)
	}
	if cs.QuestionID != nil {
		cs.where(query, Tables.Comment.Alias, Columns.Comment.QuestionID, cs.QuestionID)
	}
	if cs.TestAssignmentID != nil {
		cs.where(query, Tables.Comment.Alias, Columns.Comment.TestAssignmentID, cs.TestAssignmentID)
	}
	if cs.TaskID != nil {
		cs.where(query, Tables.Comment.Alias, Columns.Comment.TaskID, cs.TaskID)
	}
	if len(cs.IDs) > 0 {
		Filter{Columns.Comment.ID, cs.IDs, SearchTypeArray, false}.Apply(query)
	}
	if cs.ContentILike != nil {
		Filter{Columns.Comment.Content, *cs.ContentILike, SearchTypeILike, false}.Apply(query)
	}

	cs.apply(query)

	return query
}

func (cs *CommentSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if cs == nil {
			return query, nil
		}
		return cs.Apply(query), nil
	}
}

type CompanySearch struct {
	search

	ID        *int64
	Name      *string
	IDs       []int64
	NameILike *string
}

func (cs *CompanySearch) Apply(query *orm.Query) *orm.Query {
	if cs == nil {
		return query
	}
	if cs.ID != nil {
		cs.where(query, Tables.Company.Alias, Columns.Company.ID, cs.ID)
	}
	if cs.Name != nil {
		cs.where(query, Tables.Company.Alias, Columns.Company.Name, cs.Name)
	}
	if len(cs.IDs) > 0 {
		Filter{Columns.Company.ID, cs.IDs, SearchTypeArray, false}.Apply(query)
	}
	if cs.NameILike != nil {
		Filter{Columns.Company.Name, *cs.NameILike, SearchTypeILike, false}.Apply(query)
	}

	cs.apply(query)

	return query
}

func (cs *CompanySearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if cs == nil {
			return query, nil
		}
		return cs.Apply(query), nil
	}
}

type InterviewSearch struct {
	search

	ID              *int64
	SourceID        *int64
	Slug            *string
	Title           *string
	CompanyID       *int64
	YoutubeUrl      *string
	VfsPath         *string
	SourceUrl       *string
	IsEmbeddable    *bool
	IsReal          *bool
	IsVisible       *bool
	PublishedDate   *time.Time
	CreatedAt       *time.Time
	IDs             []int64
	SlugILike       *string
	TitleILike      *string
	YoutubeUrlILike *string
	VfsPathILike    *string
	SourceUrlILike  *string
}

func (is *InterviewSearch) Apply(query *orm.Query) *orm.Query {
	if is == nil {
		return query
	}
	if is.ID != nil {
		is.where(query, Tables.Interview.Alias, Columns.Interview.ID, is.ID)
	}
	if is.SourceID != nil {
		is.where(query, Tables.Interview.Alias, Columns.Interview.SourceID, is.SourceID)
	}
	if is.Slug != nil {
		is.where(query, Tables.Interview.Alias, Columns.Interview.Slug, is.Slug)
	}
	if is.Title != nil {
		is.where(query, Tables.Interview.Alias, Columns.Interview.Title, is.Title)
	}
	if is.CompanyID != nil {
		is.where(query, Tables.Interview.Alias, Columns.Interview.CompanyID, is.CompanyID)
	}
	if is.YoutubeUrl != nil {
		is.where(query, Tables.Interview.Alias, Columns.Interview.YoutubeUrl, is.YoutubeUrl)
	}
	if is.VfsPath != nil {
		is.where(query, Tables.Interview.Alias, Columns.Interview.VfsPath, is.VfsPath)
	}
	if is.SourceUrl != nil {
		is.where(query, Tables.Interview.Alias, Columns.Interview.SourceUrl, is.SourceUrl)
	}
	if is.IsEmbeddable != nil {
		is.where(query, Tables.Interview.Alias, Columns.Interview.IsEmbeddable, is.IsEmbeddable)
	}
	if is.IsReal != nil {
		is.where(query, Tables.Interview.Alias, Columns.Interview.IsReal, is.IsReal)
	}
	if is.IsVisible != nil {
		is.where(query, Tables.Interview.Alias, Columns.Interview.IsVisible, is.IsVisible)
	}
	if is.PublishedDate != nil {
		is.where(query, Tables.Interview.Alias, Columns.Interview.PublishedDate, is.PublishedDate)
	}
	if is.CreatedAt != nil {
		is.where(query, Tables.Interview.Alias, Columns.Interview.CreatedAt, is.CreatedAt)
	}
	if len(is.IDs) > 0 {
		Filter{Columns.Interview.ID, is.IDs, SearchTypeArray, false}.Apply(query)
	}
	if is.SlugILike != nil {
		Filter{Columns.Interview.Slug, *is.SlugILike, SearchTypeILike, false}.Apply(query)
	}
	if is.TitleILike != nil {
		Filter{Columns.Interview.Title, *is.TitleILike, SearchTypeILike, false}.Apply(query)
	}
	if is.YoutubeUrlILike != nil {
		Filter{Columns.Interview.YoutubeUrl, *is.YoutubeUrlILike, SearchTypeILike, false}.Apply(query)
	}
	if is.VfsPathILike != nil {
		Filter{Columns.Interview.VfsPath, *is.VfsPathILike, SearchTypeILike, false}.Apply(query)
	}
	if is.SourceUrlILike != nil {
		Filter{Columns.Interview.SourceUrl, *is.SourceUrlILike, SearchTypeILike, false}.Apply(query)
	}

	is.apply(query)

	return query
}

func (is *InterviewSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if is == nil {
			return query, nil
		}
		return is.Apply(query), nil
	}
}

type QuestionSearch struct {
	search

	ID           *int64
	SourceID     *int64
	Slug         *string
	Content      *string
	Frequency    *float32
	CreatedAt    *time.Time
	IDs          []int64
	SlugILike    *string
	ContentILike *string
}

func (qs *QuestionSearch) Apply(query *orm.Query) *orm.Query {
	if qs == nil {
		return query
	}
	if qs.ID != nil {
		qs.where(query, Tables.Question.Alias, Columns.Question.ID, qs.ID)
	}
	if qs.SourceID != nil {
		qs.where(query, Tables.Question.Alias, Columns.Question.SourceID, qs.SourceID)
	}
	if qs.Slug != nil {
		qs.where(query, Tables.Question.Alias, Columns.Question.Slug, qs.Slug)
	}
	if qs.Content != nil {
		qs.where(query, Tables.Question.Alias, Columns.Question.Content, qs.Content)
	}
	if qs.Frequency != nil {
		qs.where(query, Tables.Question.Alias, Columns.Question.Frequency, qs.Frequency)
	}
	if qs.CreatedAt != nil {
		qs.where(query, Tables.Question.Alias, Columns.Question.CreatedAt, qs.CreatedAt)
	}
	if len(qs.IDs) > 0 {
		Filter{Columns.Question.ID, qs.IDs, SearchTypeArray, false}.Apply(query)
	}
	if qs.SlugILike != nil {
		Filter{Columns.Question.Slug, *qs.SlugILike, SearchTypeILike, false}.Apply(query)
	}
	if qs.ContentILike != nil {
		Filter{Columns.Question.Content, *qs.ContentILike, SearchTypeILike, false}.Apply(query)
	}

	qs.apply(query)

	return query
}

func (qs *QuestionSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if qs == nil {
			return query, nil
		}
		return qs.Apply(query), nil
	}
}

type QuestionsGradeSearch struct {
	search

	QuestionID  *int64
	Grade       *string
	Frequency   *float32
	QuestionIDs []int64
	Grades      []string
	GradeILike  *string
}

func (qgs *QuestionsGradeSearch) Apply(query *orm.Query) *orm.Query {
	if qgs == nil {
		return query
	}
	if qgs.QuestionID != nil {
		qgs.where(query, Tables.QuestionsGrade.Alias, Columns.QuestionsGrade.QuestionID, qgs.QuestionID)
	}
	if qgs.Grade != nil {
		qgs.where(query, Tables.QuestionsGrade.Alias, Columns.QuestionsGrade.Grade, qgs.Grade)
	}
	if qgs.Frequency != nil {
		qgs.where(query, Tables.QuestionsGrade.Alias, Columns.QuestionsGrade.Frequency, qgs.Frequency)
	}
	if len(qgs.QuestionIDs) > 0 {
		Filter{Columns.QuestionsGrade.QuestionID, qgs.QuestionIDs, SearchTypeArray, false}.Apply(query)
	}
	if len(qgs.Grades) > 0 {
		Filter{Columns.QuestionsGrade.Grade, qgs.Grades, SearchTypeArray, false}.Apply(query)
	}
	if qgs.GradeILike != nil {
		Filter{Columns.QuestionsGrade.Grade, *qgs.GradeILike, SearchTypeILike, false}.Apply(query)
	}

	qgs.apply(query)

	return query
}

func (qgs *QuestionsGradeSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if qgs == nil {
			return query, nil
		}
		return qgs.Apply(query), nil
	}
}

type SkillSearch struct {
	search

	ID        *int64
	Name      *string
	IDs       []int64
	NameILike *string
}

func (ss *SkillSearch) Apply(query *orm.Query) *orm.Query {
	if ss == nil {
		return query
	}
	if ss.ID != nil {
		ss.where(query, Tables.Skill.Alias, Columns.Skill.ID, ss.ID)
	}
	if ss.Name != nil {
		ss.where(query, Tables.Skill.Alias, Columns.Skill.Name, ss.Name)
	}
	if len(ss.IDs) > 0 {
		Filter{Columns.Skill.ID, ss.IDs, SearchTypeArray, false}.Apply(query)
	}
	if ss.NameILike != nil {
		Filter{Columns.Skill.Name, *ss.NameILike, SearchTypeILike, false}.Apply(query)
	}

	ss.apply(query)

	return query
}

func (ss *SkillSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if ss == nil {
			return query, nil
		}
		return ss.Apply(query), nil
	}
}

type TaskSearch struct {
	search

	ID             *int64
	SourceID       *int64
	Slug           *string
	Title          *string
	Type           *string
	Content        *string
	SourceUrl      *string
	Rank           *int
	LastDate       *time.Time
	CreatedAt      *time.Time
	IDs            []int64
	SlugILike      *string
	TitleILike     *string
	TypeILike      *string
	ContentILike   *string
	SourceUrlILike *string
}

func (ts *TaskSearch) Apply(query *orm.Query) *orm.Query {
	if ts == nil {
		return query
	}
	if ts.ID != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.ID, ts.ID)
	}
	if ts.SourceID != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.SourceID, ts.SourceID)
	}
	if ts.Slug != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.Slug, ts.Slug)
	}
	if ts.Title != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.Title, ts.Title)
	}
	if ts.Type != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.Type, ts.Type)
	}
	if ts.Content != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.Content, ts.Content)
	}
	if ts.SourceUrl != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.SourceUrl, ts.SourceUrl)
	}
	if ts.Rank != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.Rank, ts.Rank)
	}
	if ts.LastDate != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.LastDate, ts.LastDate)
	}
	if ts.CreatedAt != nil {
		ts.where(query, Tables.Task.Alias, Columns.Task.CreatedAt, ts.CreatedAt)
	}
	if len(ts.IDs) > 0 {
		Filter{Columns.Task.ID, ts.IDs, SearchTypeArray, false}.Apply(query)
	}
	if ts.SlugILike != nil {
		Filter{Columns.Task.Slug, *ts.SlugILike, SearchTypeILike, false}.Apply(query)
	}
	if ts.TitleILike != nil {
		Filter{Columns.Task.Title, *ts.TitleILike, SearchTypeILike, false}.Apply(query)
	}
	if ts.TypeILike != nil {
		Filter{Columns.Task.Type, *ts.TypeILike, SearchTypeILike, false}.Apply(query)
	}
	if ts.ContentILike != nil {
		Filter{Columns.Task.Content, *ts.ContentILike, SearchTypeILike, false}.Apply(query)
	}
	if ts.SourceUrlILike != nil {
		Filter{Columns.Task.SourceUrl, *ts.SourceUrlILike, SearchTypeILike, false}.Apply(query)
	}

	ts.apply(query)

	return query
}

func (ts *TaskSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if ts == nil {
			return query, nil
		}
		return ts.Apply(query), nil
	}
}

type TasksCompanySearch struct {
	search

	TaskID     *int64
	CompanyID  *int64
	TaskIDs    []int64
	CompanyIDs []int64
}

func (tcs *TasksCompanySearch) Apply(query *orm.Query) *orm.Query {
	if tcs == nil {
		return query
	}
	if tcs.TaskID != nil {
		tcs.where(query, Tables.TasksCompany.Alias, Columns.TasksCompany.TaskID, tcs.TaskID)
	}
	if tcs.CompanyID != nil {
		tcs.where(query, Tables.TasksCompany.Alias, Columns.TasksCompany.CompanyID, tcs.CompanyID)
	}
	if len(tcs.TaskIDs) > 0 {
		Filter{Columns.TasksCompany.TaskID, tcs.TaskIDs, SearchTypeArray, false}.Apply(query)
	}
	if len(tcs.CompanyIDs) > 0 {
		Filter{Columns.TasksCompany.CompanyID, tcs.CompanyIDs, SearchTypeArray, false}.Apply(query)
	}

	tcs.apply(query)

	return query
}

func (tcs *TasksCompanySearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if tcs == nil {
			return query, nil
		}
		return tcs.Apply(query), nil
	}
}

type TestAssignmentSearch struct {
	search

	ID             *int64
	Slug           *string
	Title          *string
	Content        *string
	SourceUrl      *string
	PublishedDate  *time.Time
	CreatedAt      *time.Time
	IDs            []int64
	SlugILike      *string
	TitleILike     *string
	ContentILike   *string
	SourceUrlILike *string
}

func (tas *TestAssignmentSearch) Apply(query *orm.Query) *orm.Query {
	if tas == nil {
		return query
	}
	if tas.ID != nil {
		tas.where(query, Tables.TestAssignment.Alias, Columns.TestAssignment.ID, tas.ID)
	}
	if tas.Slug != nil {
		tas.where(query, Tables.TestAssignment.Alias, Columns.TestAssignment.Slug, tas.Slug)
	}
	if tas.Title != nil {
		tas.where(query, Tables.TestAssignment.Alias, Columns.TestAssignment.Title, tas.Title)
	}
	if tas.Content != nil {
		tas.where(query, Tables.TestAssignment.Alias, Columns.TestAssignment.Content, tas.Content)
	}
	if tas.SourceUrl != nil {
		tas.where(query, Tables.TestAssignment.Alias, Columns.TestAssignment.SourceUrl, tas.SourceUrl)
	}
	if tas.PublishedDate != nil {
		tas.where(query, Tables.TestAssignment.Alias, Columns.TestAssignment.PublishedDate, tas.PublishedDate)
	}
	if tas.CreatedAt != nil {
		tas.where(query, Tables.TestAssignment.Alias, Columns.TestAssignment.CreatedAt, tas.CreatedAt)
	}
	if len(tas.IDs) > 0 {
		Filter{Columns.TestAssignment.ID, tas.IDs, SearchTypeArray, false}.Apply(query)
	}
	if tas.SlugILike != nil {
		Filter{Columns.TestAssignment.Slug, *tas.SlugILike, SearchTypeILike, false}.Apply(query)
	}
	if tas.TitleILike != nil {
		Filter{Columns.TestAssignment.Title, *tas.TitleILike, SearchTypeILike, false}.Apply(query)
	}
	if tas.ContentILike != nil {
		Filter{Columns.TestAssignment.Content, *tas.ContentILike, SearchTypeILike, false}.Apply(query)
	}
	if tas.SourceUrlILike != nil {
		Filter{Columns.TestAssignment.SourceUrl, *tas.SourceUrlILike, SearchTypeILike, false}.Apply(query)
	}

	tas.apply(query)

	return query
}

func (tas *TestAssignmentSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if tas == nil {
			return query, nil
		}
		return tas.Apply(query), nil
	}
}

type TestAssignmentsCompanySearch struct {
	search

	TestAssignmentID  *int64
	CompanyID         *int64
	TestAssignmentIDs []int64
	CompanyIDs        []int64
}

func (tacs *TestAssignmentsCompanySearch) Apply(query *orm.Query) *orm.Query {
	if tacs == nil {
		return query
	}
	if tacs.TestAssignmentID != nil {
		tacs.where(query, Tables.TestAssignmentsCompany.Alias, Columns.TestAssignmentsCompany.TestAssignmentID, tacs.TestAssignmentID)
	}
	if tacs.CompanyID != nil {
		tacs.where(query, Tables.TestAssignmentsCompany.Alias, Columns.TestAssignmentsCompany.CompanyID, tacs.CompanyID)
	}
	if len(tacs.TestAssignmentIDs) > 0 {
		Filter{Columns.TestAssignmentsCompany.TestAssignmentID, tacs.TestAssignmentIDs, SearchTypeArray, false}.Apply(query)
	}
	if len(tacs.CompanyIDs) > 0 {
		Filter{Columns.TestAssignmentsCompany.CompanyID, tacs.CompanyIDs, SearchTypeArray, false}.Apply(query)
	}

	tacs.apply(query)

	return query
}

func (tacs *TestAssignmentsCompanySearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if tacs == nil {
			return query, nil
		}
		return tacs.Apply(query), nil
	}
}

type TestAssignmentsSkillSearch struct {
	search

	TestAssignmentID  *int64
	SkillID           *int64
	TestAssignmentIDs []int64
	SkillIDs          []int64
}

func (tass *TestAssignmentsSkillSearch) Apply(query *orm.Query) *orm.Query {
	if tass == nil {
		return query
	}
	if tass.TestAssignmentID != nil {
		tass.where(query, Tables.TestAssignmentsSkill.Alias, Columns.TestAssignmentsSkill.TestAssignmentID, tass.TestAssignmentID)
	}
	if tass.SkillID != nil {
		tass.where(query, Tables.TestAssignmentsSkill.Alias, Columns.TestAssignmentsSkill.SkillID, tass.SkillID)
	}
	if len(tass.TestAssignmentIDs) > 0 {
		Filter{Columns.TestAssignmentsSkill.TestAssignmentID, tass.TestAssignmentIDs, SearchTypeArray, false}.Apply(query)
	}
	if len(tass.SkillIDs) > 0 {
		Filter{Columns.TestAssignmentsSkill.SkillID, tass.SkillIDs, SearchTypeArray, false}.Apply(query)
	}

	tass.apply(query)

	return query
}

func (tass *TestAssignmentsSkillSearch) Q() applier {
	return func(query *orm.Query) (*orm.Query, error) {
		if tass == nil {
			return query, nil
		}
		return tass.Apply(query), nil
	}
}
