// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"time"
)

var Columns = struct {
	User struct {
		ID, CreatedAt string
	}
	Comment struct {
		ID, Content, LikesCnt, UserID, IsVisible, CreatedAt, InterviewID, QuestionID, TestAssignmentID, TaskID string

		User, Interview, Question, TestAssignment, Task string
	}
	Company struct {
		ID, Name string
	}
	Interview struct {
		ID, SourceID, Slug, Title, Grades, Types, CompanyID, YoutubeUrl, VfsPath, SourceUrl, IsEmbeddable, IsReal, IsVisible, PublishedDate, CreatedAt string

		Company string
	}
	Question struct {
		ID, SourceID, Slug, Content, Frequency, CreatedAt string
	}
	QuestionsGrade struct {
		QuestionID, Grade, Frequency string

		Question string
	}
	Skill struct {
		ID, Name string
	}
	Task struct {
		ID, SourceID, Slug, Title, Grades, Type, Content, SourceUrl, Rank, LastDate, CreatedAt string
	}
	TasksCompany struct {
		TaskID, CompanyID string

		Task, Company string
	}
	TestAssignment struct {
		ID, Slug, Title, Grades, Content, SourceUrl, PublishedDate, CreatedAt string
	}
	TestAssignmentsCompany struct {
		TestAssignmentID, CompanyID string

		TestAssignment, Company string
	}
	TestAssignmentsSkill struct {
		TestAssignmentID, SkillID string

		TestAssignment, Skill string
	}
}{
	User: struct {
		ID, CreatedAt string
	}{
		ID:        "userId",
		CreatedAt: "createdAt",
	},
	Comment: struct {
		ID, Content, LikesCnt, UserID, IsVisible, CreatedAt, InterviewID, QuestionID, TestAssignmentID, TaskID string

		User, Interview, Question, TestAssignment, Task string
	}{
		ID:               "commentId",
		Content:          "content",
		LikesCnt:         "likesCnt",
		UserID:           "userId",
		IsVisible:        "isVisible",
		CreatedAt:        "createdAt",
		InterviewID:      "interviewId",
		QuestionID:       "questionId",
		TestAssignmentID: "testAssignmentId",
		TaskID:           "taskId",

		User:           "User",
		Interview:      "Interview",
		Question:       "Question",
		TestAssignment: "TestAssignment",
		Task:           "Task",
	},
	Company: struct {
		ID, Name string
	}{
		ID:   "companyId",
		Name: "name",
	},
	Interview: struct {
		ID, SourceID, Slug, Title, Grades, Types, CompanyID, YoutubeUrl, VfsPath, SourceUrl, IsEmbeddable, IsReal, IsVisible, PublishedDate, CreatedAt string

		Company string
	}{
		ID:            "interviewId",
		SourceID:      "sourceId",
		Slug:          "slug",
		Title:         "title",
		Grades:        "grades",
		Types:         "types",
		CompanyID:     "companyId",
		YoutubeUrl:    "youtubeUrl",
		VfsPath:       "vfsPath",
		SourceUrl:     "sourceUrl",
		IsEmbeddable:  "isEmbeddable",
		IsReal:        "isReal",
		IsVisible:     "isVisible",
		PublishedDate: "publishedDate",
		CreatedAt:     "createdAt",

		Company: "Company",
	},
	Question: struct {
		ID, SourceID, Slug, Content, Frequency, CreatedAt string
	}{
		ID:        "questionId",
		SourceID:  "sourceId",
		Slug:      "slug",
		Content:   "content",
		Frequency: "frequency",
		CreatedAt: "createdAt",
	},
	QuestionsGrade: struct {
		QuestionID, Grade, Frequency string

		Question string
	}{
		QuestionID: "questionId",
		Grade:      "grade",
		Frequency:  "frequency",

		Question: "Question",
	},
	Skill: struct {
		ID, Name string
	}{
		ID:   "skillId",
		Name: "name",
	},
	Task: struct {
		ID, SourceID, Slug, Title, Grades, Type, Content, SourceUrl, Rank, LastDate, CreatedAt string
	}{
		ID:        "taskId",
		SourceID:  "sourceId",
		Slug:      "slug",
		Title:     "title",
		Grades:    "grades",
		Type:      "type",
		Content:   "content",
		SourceUrl: "sourceUrl",
		Rank:      "rank",
		LastDate:  "lastDate",
		CreatedAt: "createdAt",
	},
	TasksCompany: struct {
		TaskID, CompanyID string

		Task, Company string
	}{
		TaskID:    "taskId",
		CompanyID: "companyId",

		Task:    "Task",
		Company: "Company",
	},
	TestAssignment: struct {
		ID, Slug, Title, Grades, Content, SourceUrl, PublishedDate, CreatedAt string
	}{
		ID:            "testAssignmentId",
		Slug:          "slug",
		Title:         "title",
		Grades:        "grades",
		Content:       "content",
		SourceUrl:     "sourceUrl",
		PublishedDate: "publishedDate",
		CreatedAt:     "createdAt",
	},
	TestAssignmentsCompany: struct {
		TestAssignmentID, CompanyID string

		TestAssignment, Company string
	}{
		TestAssignmentID: "testAssignmentId",
		CompanyID:        "companyId",

		TestAssignment: "TestAssignment",
		Company:        "Company",
	},
	TestAssignmentsSkill: struct {
		TestAssignmentID, SkillID string

		TestAssignment, Skill string
	}{
		TestAssignmentID: "testAssignmentId",
		SkillID:          "skillId",

		TestAssignment: "TestAssignment",
		Skill:          "Skill",
	},
}

var Tables = struct {
	User struct {
		Name, Alias string
	}
	Comment struct {
		Name, Alias string
	}
	Company struct {
		Name, Alias string
	}
	Interview struct {
		Name, Alias string
	}
	Question struct {
		Name, Alias string
	}
	QuestionsGrade struct {
		Name, Alias string
	}
	Skill struct {
		Name, Alias string
	}
	Task struct {
		Name, Alias string
	}
	TasksCompany struct {
		Name, Alias string
	}
	TestAssignment struct {
		Name, Alias string
	}
	TestAssignmentsCompany struct {
		Name, Alias string
	}
	TestAssignmentsSkill struct {
		Name, Alias string
	}
}{
	User: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
	Comment: struct {
		Name, Alias string
	}{
		Name:  "comments",
		Alias: "t",
	},
	Company: struct {
		Name, Alias string
	}{
		Name:  "companies",
		Alias: "t",
	},
	Interview: struct {
		Name, Alias string
	}{
		Name:  "interviews",
		Alias: "t",
	},
	Question: struct {
		Name, Alias string
	}{
		Name:  "questions",
		Alias: "t",
	},
	QuestionsGrade: struct {
		Name, Alias string
	}{
		Name:  "questionsGrades",
		Alias: "t",
	},
	Skill: struct {
		Name, Alias string
	}{
		Name:  "skills",
		Alias: "t",
	},
	Task: struct {
		Name, Alias string
	}{
		Name:  "tasks",
		Alias: "t",
	},
	TasksCompany: struct {
		Name, Alias string
	}{
		Name:  "tasksCompanies",
		Alias: "t",
	},
	TestAssignment: struct {
		Name, Alias string
	}{
		Name:  "testAssignments",
		Alias: "t",
	},
	TestAssignmentsCompany: struct {
		Name, Alias string
	}{
		Name:  "testAssignmentsCompanies",
		Alias: "t",
	},
	TestAssignmentsSkill: struct {
		Name, Alias string
	}{
		Name:  "testAssignmentsSkills",
		Alias: "t",
	},
}

type User struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID        int64     `pg:"userId,pk"`
	CreatedAt time.Time `pg:"createdAt,use_zero"`
}

type Comment struct {
	tableName struct{} `pg:"comments,alias:t,discard_unknown_columns"`

	ID               int64     `pg:"commentId,pk"`
	Content          string    `pg:"content,use_zero"`
	LikesCnt         int64     `pg:"likesCnt,use_zero"`
	UserID           *int64    `pg:"userId"`
	IsVisible        bool      `pg:"isVisible,use_zero"`
	CreatedAt        time.Time `pg:"createdAt,use_zero"`
	InterviewID      *int64    `pg:"interviewId"`
	QuestionID       *int64    `pg:"questionId"`
	TestAssignmentID *int64    `pg:"testAssignmentId"`
	TaskID           *int64    `pg:"taskId"`

	User           *User           `pg:"fk:userId,rel:has-one"`
	Interview      *Interview      `pg:"fk:interviewId,rel:has-one"`
	Question       *Question       `pg:"fk:questionId,rel:has-one"`
	TestAssignment *TestAssignment `pg:"fk:testAssignmentId,rel:has-one"`
	Task           *Task           `pg:"fk:taskId,rel:has-one"`
}

type Company struct {
	tableName struct{} `pg:"companies,alias:t,discard_unknown_columns"`

	ID   int64  `pg:"companyId,pk"`
	Name string `pg:"name,use_zero"`
}

type Interview struct {
	tableName struct{} `pg:"interviews,alias:t,discard_unknown_columns"`

	ID            int64      `pg:"interviewId,pk"`
	SourceID      *int64     `pg:"sourceId"`
	Slug          string     `pg:"slug,use_zero"`
	Title         string     `pg:"title,use_zero"`
	Grades        []string   `pg:"grades,array,use_zero"`
	Types         []string   `pg:"types,array,use_zero"`
	CompanyID     *int64     `pg:"companyId"`
	YoutubeUrl    *string    `pg:"youtubeUrl"`
	VfsPath       *string    `pg:"vfsPath"`
	SourceUrl     *string    `pg:"sourceUrl"`
	IsEmbeddable  bool       `pg:"isEmbeddable,use_zero"`
	IsReal        bool       `pg:"isReal,use_zero"`
	IsVisible     bool       `pg:"isVisible,use_zero"`
	PublishedDate *time.Time `pg:"publishedDate"`
	CreatedAt     time.Time  `pg:"createdAt,use_zero"`

	Company *Company `pg:"fk:companyId,rel:has-one"`
}

type Question struct {
	tableName struct{} `pg:"questions,alias:t,discard_unknown_columns"`

	ID        int64     `pg:"questionId,pk"`
	SourceID  int64     `pg:"sourceId,use_zero"`
	Slug      string    `pg:"slug,use_zero"`
	Content   string    `pg:"content,use_zero"`
	Frequency *float32  `pg:"frequency"`
	CreatedAt time.Time `pg:"createdAt,use_zero"`
}

type QuestionsGrade struct {
	tableName struct{} `pg:"questionsGrades,alias:t,discard_unknown_columns"`

	QuestionID int64   `pg:"questionId,pk"`
	Grade      string  `pg:"grade,pk"`
	Frequency  float32 `pg:"frequency,use_zero"`

	Question *Question `pg:"fk:questionId,rel:has-one"`
}

type Skill struct {
	tableName struct{} `pg:"skills,alias:t,discard_unknown_columns"`

	ID   int64  `pg:"skillId,pk"`
	Name string `pg:"name,use_zero"`
}

type Task struct {
	tableName struct{} `pg:"tasks,alias:t,discard_unknown_columns"`

	ID        int64      `pg:"taskId,pk"`
	SourceID  int64      `pg:"sourceId,use_zero"`
	Slug      string     `pg:"slug,use_zero"`
	Title     string     `pg:"title,use_zero"`
	Grades    []string   `pg:"grades,array,use_zero"`
	Type      *string    `pg:"type"`
	Content   string     `pg:"content,use_zero"`
	SourceUrl *string    `pg:"sourceUrl"`
	Rank      *int       `pg:"rank"`
	LastDate  *time.Time `pg:"lastDate"`
	CreatedAt time.Time  `pg:"createdAt,use_zero"`
}

type TasksCompany struct {
	tableName struct{} `pg:"tasksCompanies,alias:t,discard_unknown_columns"`

	TaskID    int64 `pg:"taskId,pk"`
	CompanyID int64 `pg:"companyId,pk"`

	Task    *Task    `pg:"fk:taskId,rel:has-one"`
	Company *Company `pg:"fk:companyId,rel:has-one"`
}

type TestAssignment struct {
	tableName struct{} `pg:"testAssignments,alias:t,discard_unknown_columns"`

	ID            int64      `pg:"testAssignmentId,pk"`
	Slug          string     `pg:"slug,use_zero"`
	Title         string     `pg:"title,use_zero"`
	Grades        []string   `pg:"grades,array,use_zero"`
	Content       string     `pg:"content,use_zero"`
	SourceUrl     *string    `pg:"sourceUrl"`
	PublishedDate *time.Time `pg:"publishedDate"`
	CreatedAt     time.Time  `pg:"createdAt,use_zero"`
}

type TestAssignmentsCompany struct {
	tableName struct{} `pg:"testAssignmentsCompanies,alias:t,discard_unknown_columns"`

	TestAssignmentID int64 `pg:"testAssignmentId,pk"`
	CompanyID        int64 `pg:"companyId,pk"`

	TestAssignment *TestAssignment `pg:"fk:testAssignmentId,rel:has-one"`
	Company        *Company        `pg:"fk:companyId,rel:has-one"`
}

type TestAssignmentsSkill struct {
	tableName struct{} `pg:"testAssignmentsSkills,alias:t,discard_unknown_columns"`

	TestAssignmentID int64 `pg:"testAssignmentId,pk"`
	SkillID          int64 `pg:"skillId,pk"`

	TestAssignment *TestAssignment `pg:"fk:testAssignmentId,rel:has-one"`
	Skill          *Skill          `pg:"fk:skillId,rel:has-one"`
}
