// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"unicode/utf8"
)

const (
	ErrEmptyValue = "empty"
	ErrMaxLength  = "len"
	ErrWrongValue = "value"
)

func (c Company) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(c.Name) > 255 {
		errors[Columns.Company.Name] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (i Interview) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(i.Slug) > 255 {
		errors[Columns.Interview.Slug] = ErrMaxLength
	}

	if utf8.RuneCountInString(i.Title) > 255 {
		errors[Columns.Interview.Title] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (q Question) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(q.Slug) > 255 {
		errors[Columns.Question.Slug] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (s Skill) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(s.Name) > 255 {
		errors[Columns.Skill.Name] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (t Task) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(t.Slug) > 255 {
		errors[Columns.Task.Slug] = ErrMaxLength
	}

	if utf8.RuneCountInString(t.Title) > 255 {
		errors[Columns.Task.Title] = ErrMaxLength
	}

	if t.Type != nil && utf8.RuneCountInString(*t.Type) > 20 {
		errors[Columns.Task.Type] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (ta TestAssignment) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(ta.Slug) > 255 {
		errors[Columns.TestAssignment.Slug] = ErrMaxLength
	}

	if utf8.RuneCountInString(ta.Title) > 255 {
		errors[Columns.TestAssignment.Title] = ErrMaxLength
	}

	return errors, len(errors) == 0
}
