// Code generated by zenrpc v2.3.1; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	QuestionService struct{ List, Get string }
}{
	QuestionService: struct{ List, Get string }{
		List: "list",
		Get:  "get",
	},
}

func (QuestionService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"List": {
				Description: `List returns a page of questions ordered by chance, highest first.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "page",
						Optional:    true,
						Description: `page number, starts at 1`,
						Type:        smd.Integer,
					},
					{
						Name:        "pageSize",
						Optional:    true,
						Description: `items per page, capped at 100`,
						Type:        smd.Integer,
					},
					{
						Name:        "search",
						Optional:    true,
						Description: `substring to search in question text`,
						Type:        smd.String,
					},
					{
						Name:        "grade",
						Optional:    true,
						Description: `filter by grade: junior, middle, senior or lead`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Description: `questions page with total count`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "QuestionList",
					Properties: smd.PropertyList{
						{
							Name: "items",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/Question",
							},
						},
						{
							Name: "totalCount",
							Type: smd.Integer,
						},
					},
					Definitions: map[string]smd.Definition{
						"Question": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "id",
									Type: smd.Integer,
								},
								{
									Name: "slug",
									Type: smd.String,
								},
								{
									Name: "content",
									Type: smd.String,
								},
								{
									Name:     "chance",
									Optional: true,
									Description: `Chance is the overall probability of getting this question, 0..100.
Null when the source has no statistics for it.`,
									Type: smd.Float,
								},
								{
									Name:     "gradeChance",
									Optional: true,
									Description: `GradeChance is the probability for a single grade. Filled in only when the
list is filtered by grade, null otherwise.`,
									Type: smd.Float,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					500: "internal error",
				},
			},
			"Get": {
				Description: `Get returns a single question by id.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "id",
						Description: `question id`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Description: `question`,
					Optional:    true,
					Type:        smd.Object,
					TypeName:    "Question",
					Properties: smd.PropertyList{
						{
							Name: "id",
							Type: smd.Integer,
						},
						{
							Name: "slug",
							Type: smd.String,
						},
						{
							Name: "content",
							Type: smd.String,
						},
						{
							Name:     "chance",
							Optional: true,
							Description: `Chance is the overall probability of getting this question, 0..100.
Null when the source has no statistics for it.`,
							Type: smd.Float,
						},
						{
							Name:     "gradeChance",
							Optional: true,
							Description: `GradeChance is the probability for a single grade. Filled in only when the
list is filtered by grade, null otherwise.`,
							Type: smd.Float,
						},
					},
				},
				Errors: map[int]string{
					404: "question not found",
					500: "internal error",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s QuestionService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.QuestionService.List:
		var args = struct {
			Page     *int    `json:"page"`
			PageSize *int    `json:"pageSize"`
			Search   *string `json:"search"`
			Grade    *string `json:"grade"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"page", "pageSize", "search", "grade"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		//zenrpc:page=1 page number, starts at 1
		if args.Page == nil {
			var v int = 1
			args.Page = &v
		}

		//zenrpc:pageSize=25 items per page, capped at 100
		if args.PageSize == nil {
			var v int = 25
			args.PageSize = &v
		}

		resp.Set(s.List(ctx, *args.Page, *args.PageSize, args.Search, args.Grade))

	case RPC.QuestionService.Get:
		var args = struct {
			Id int64 `json:"id"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"id"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Get(ctx, args.Id))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
