CREATE TABLE "comments" (
	"commentId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"content" text NOT NULL,
	"likesCnt" bigint NOT NULL DEFAULT 0,
	"userId" bigint,
	"isVisible" boolean NOT NULL DEFAULT true,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"interviewId" bigint,
	"questionId" bigint,
	"testAssignmentId" bigint,
	"taskId" bigint,
	CONSTRAINT "pk_comments" PRIMARY KEY("commentId"),
	CONSTRAINT "chk_comments_oneEntity" CHECK((("interviewId" IS NOT NULL)::int + ("questionId" IS NOT NULL)::int + ("testAssignmentId" IS NOT NULL)::int + ("taskId" IS NOT NULL)::int) = 1),
	CONSTRAINT "chk_comments_likesCnt" CHECK("likesCnt" >= 0)
);

CREATE TABLE "companies" (
	"companyId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	CONSTRAINT "pk_companies" PRIMARY KEY("companyId"),
	UNIQUE("name")
);

CREATE TABLE "interviews" (
	"interviewId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"sourceId" bigint,
	"slug" varchar(255) NOT NULL,
	"title" varchar(255) NOT NULL,
	"grades" varchar[] NOT NULL DEFAULT '{}',
	"types" varchar[] NOT NULL DEFAULT '{}',
	"companyId" bigint,
	"youtubeUrl" text,
	"vfsPath" text,
	"sourceUrl" text,
	"isEmbeddable" boolean NOT NULL DEFAULT false,
	"isReal" boolean NOT NULL DEFAULT true,
	"isVisible" boolean NOT NULL DEFAULT true,
	"publishedDate" date,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT "pk_interviews" PRIMARY KEY("interviewId"),
	UNIQUE("slug"),
	UNIQUE("sourceId"),
	CONSTRAINT "chk_interviews_grades" CHECK("grades" <@ ARRAY['junior','middle','senior','lead']::varchar[]),
	CONSTRAINT "chk_interviews_types" CHECK("types" <@ ARRAY['technical','liveCoding','algorithmic','hrScreening','final','systemDesign']::varchar[]),
	CONSTRAINT "chk_interviews_video" CHECK("youtubeUrl" IS NOT NULL OR "vfsPath" IS NOT NULL OR "sourceUrl" IS NOT NULL)
);

CREATE TABLE "questions" (
	"questionId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"sourceId" bigint NOT NULL,
	"slug" varchar(255) NOT NULL,
	"content" text NOT NULL,
	"frequency" real,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT "pk_questions" PRIMARY KEY("questionId"),
	UNIQUE("slug"),
	UNIQUE("sourceId"),
	CONSTRAINT "chk_questions_frequency" CHECK("frequency" IS NULL OR ("frequency" >= 0 AND "frequency" <= 100))
);

CREATE TABLE "questionsGrades" (
	"questionId" bigint NOT NULL,
	"grade" varchar(20) NOT NULL,
	"frequency" real NOT NULL,
	CONSTRAINT "pk_questionsGrades" PRIMARY KEY("questionId", "grade"),
	CONSTRAINT "chk_questionsGrades_grade" CHECK("grade" = ANY (ARRAY['junior','middle','senior','lead'])),
	CONSTRAINT "chk_questionsGrades_frequency" CHECK("frequency" >= 0 AND "frequency" <= 100)
);

CREATE TABLE "skills" (
	"skillId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	CONSTRAINT "pk_skills" PRIMARY KEY("skillId"),
	UNIQUE("name")
);

CREATE TABLE "tasks" (
	"taskId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"sourceId" bigint NOT NULL,
	"slug" varchar(255) NOT NULL,
	"title" varchar(255) NOT NULL,
	"grades" varchar[] NOT NULL DEFAULT '{}',
	"type" varchar(20),
	"content" text NOT NULL,
	"sourceUrl" text,
	"rank" integer,
	"lastDate" timestamptz,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT "pk_tasks" PRIMARY KEY("taskId"),
	UNIQUE("slug"),
	UNIQUE("sourceId"),
	CONSTRAINT "chk_tasks_grades" CHECK("grades" <@ ARRAY['junior','middle','senior','lead']::varchar[]),
	CONSTRAINT "chk_tasks_type" CHECK("type" IS NULL OR "type" = ANY (ARRAY['liveCoding','algorithms','systemDesign']))
);

CREATE TABLE "tasksCompanies" (
	"taskId" bigint NOT NULL,
	"companyId" bigint NOT NULL,
	CONSTRAINT "pk_tasksCompanies" PRIMARY KEY("taskId", "companyId")
);

CREATE TABLE "testAssignments" (
	"testAssignmentId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"slug" varchar(255) NOT NULL,
	"title" varchar(255) NOT NULL,
	"grades" varchar[] NOT NULL DEFAULT '{}',
	"content" text NOT NULL,
	"sourceUrl" text,
	"publishedDate" date,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT "pk_testAssignments" PRIMARY KEY("testAssignmentId"),
	UNIQUE("slug"),
	CONSTRAINT "chk_testAssignments_grades" CHECK("grades" <@ ARRAY['junior','middle','senior','lead']::varchar[])
);

CREATE TABLE "testAssignmentsCompanies" (
	"testAssignmentId" bigint NOT NULL,
	"companyId" bigint NOT NULL,
	CONSTRAINT "pk_testAssignmentsCompanies" PRIMARY KEY("testAssignmentId", "companyId")
);

CREATE TABLE "testAssignmentsSkills" (
	"testAssignmentId" bigint NOT NULL,
	"skillId" bigint NOT NULL,
	CONSTRAINT "pk_testAssignmentsSkills" PRIMARY KEY("testAssignmentId", "skillId")
);

CREATE TABLE "users" (
	"userId" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT "pk_users" PRIMARY KEY("userId")
);

CREATE INDEX "ix_comments_interviewId_createdAt" ON "comments" (
	"interviewId",
	"createdAt" DESC
);

CREATE INDEX "ix_comments_questionId_createdAt" ON "comments" (
	"questionId",
	"createdAt" DESC
);

CREATE INDEX "ix_comments_taskId_createdAt" ON "comments" (
	"taskId",
	"createdAt" DESC
);

CREATE INDEX "ix_comments_testAssignmentId_createdAt" ON "comments" (
	"testAssignmentId",
	"createdAt" DESC
);

CREATE INDEX "ix_comments_userId" ON "comments" (
	"userId"
);

CREATE INDEX "ix_interviews_companyId" ON "interviews" (
	"companyId"
);

CREATE INDEX "ix_interviews_grades" ON "interviews" USING GIN (
	"grades"
);

CREATE INDEX "ix_interviews_types" ON "interviews" USING GIN (
	"types"
);

CREATE INDEX "ix_questions_frequency" ON "questions" (
	"frequency" DESC
);

CREATE INDEX "ix_questionsGrades_grade_frequency" ON "questionsGrades" (
	"grade",
	"frequency" DESC
);

CREATE INDEX "ix_tasks_grades" ON "tasks" USING GIN (
	"grades"
);

CREATE INDEX "ix_tasks_type" ON "tasks" (
	"type"
);

CREATE INDEX "ix_tasks_rank" ON "tasks" (
	"rank"
);

CREATE INDEX "ix_tasksCompanies_companyId" ON "tasksCompanies" (
	"companyId"
);

CREATE INDEX "ix_tasksCompanies_taskId" ON "tasksCompanies" (
	"taskId"
);

CREATE INDEX "ix_testAssignments_grades" ON "testAssignments" USING GIN (
	"grades"
);

CREATE INDEX "ix_testAssignmentsCompanies_companyId" ON "testAssignmentsCompanies" (
	"companyId"
);

CREATE INDEX "ix_testAssignmentsCompanies_testAssignmentId" ON "testAssignmentsCompanies" (
	"testAssignmentId"
);

CREATE INDEX "ix_testAssignmentsSkills_skillId" ON "testAssignmentsSkills" (
	"skillId"
);

CREATE INDEX "ix_testAssignmentsSkills_testAssignmentId" ON "testAssignmentsSkills" (
	"testAssignmentId"
);

ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_interviewId" FOREIGN KEY ("interviewId")
	REFERENCES "interviews"("interviewId")
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_questionId" FOREIGN KEY ("questionId")
	REFERENCES "questions"("questionId")
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_taskId" FOREIGN KEY ("taskId")
	REFERENCES "tasks"("taskId")
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_testAssignmentId" FOREIGN KEY ("testAssignmentId")
	REFERENCES "testAssignments"("testAssignmentId")
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_userId" FOREIGN KEY ("userId")
	REFERENCES "users"("userId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "interviews" ADD CONSTRAINT "fk_interviews_companyId" FOREIGN KEY ("companyId")
	REFERENCES "companies"("companyId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "questionsGrades" ADD CONSTRAINT "fk_questionsGrades_questionId" FOREIGN KEY ("questionId")
	REFERENCES "questions"("questionId")
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "tasksCompanies" ADD CONSTRAINT "fk_tasksCompanies_companyId" FOREIGN KEY ("companyId")
	REFERENCES "companies"("companyId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "tasksCompanies" ADD CONSTRAINT "fk_tasksCompanies_taskId" FOREIGN KEY ("taskId")
	REFERENCES "tasks"("taskId")
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "testAssignmentsCompanies" ADD CONSTRAINT "fk_testAssignmentsCompanies_companyId" FOREIGN KEY ("companyId")
	REFERENCES "companies"("companyId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "testAssignmentsCompanies" ADD CONSTRAINT "fk_testAssignmentsCompanies_testAssignmentId" FOREIGN KEY ("testAssignmentId")
	REFERENCES "testAssignments"("testAssignmentId")
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "testAssignmentsSkills" ADD CONSTRAINT "fk_testAssignmentsSkills_skillId" FOREIGN KEY ("skillId")
	REFERENCES "skills"("skillId")
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "testAssignmentsSkills" ADD CONSTRAINT "fk_testAssignmentsSkills_testAssignmentId" FOREIGN KEY ("testAssignmentId")
	REFERENCES "testAssignments"("testAssignmentId")
	ON DELETE CASCADE
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

